"""Defines common constants used in several modules."""

# C_ represents a candidate in an election.
C_BIDEN = "Biden"
C_WARREN = "Warren"
C_SANDERS = "Sanders"
C_BUTTIGIEG = "Buttigieg"
C_HARRIS = "Harris"
C_YANG = "Yang"
C_OROURKE = "O'Rourke"
C_BENNET = "Bennet"
C_GABBARD = "Gabbard"
C_BOOKER = "Booker"
C_KLOBUCHAR = "Klobuchar"
C_CASTRO = "Castro"
C_STEYER = "Steyer"
C_DELANEY = "Delaney"
C_MESSAM = "Messam"
C_BULLOCK = "Bullock"
C_SESTAK = "Sestak"
C_WILLIAMSON = "Williamson"

# S_ represents a state or territory.
S_ALABAMA = "Alabama"
S_ALASKA = "Alaska"
S_AMERICAN_SAMOA = "American Samoa"
S_ARKANSAS = "Arkansas"
S_ARIZONA = "Arizona"
S_CALIFORNIA = "California"
S_COLORADO = "Colorado"
S_CONNETICUT = "Conneticut"
S_DELAWARE = "Delaware"
S_DEMOCRATS_ABROAD = "Democrats Abroad"
S_DC = "District of Columbia"
S_FLORIDA = "Florida"
S_GEORGIA = "Georgia"
S_GUAM = "Guam"
S_HAWAII = "Hawaii"
S_IDAHO = "Idaho"
S_ILLINOIS = "Illinois"
S_INDIANA = "Indiana"
S_IOWA = "Iowa"
S_KANSAS = "Kansas"
S_KENTUCKY = "Kentucky"
S_LOUISIANA = "Louisiana"
S_MAINE = "Maine"
S_MAINE1 = "Maine First Congressional District"
S_MAINE2 = "Maine Second Congressional District"
S_MARYLAND = "Maryland"
S_MASSACHUSETTS = "Massachusetts"
S_MICHIGAN = "Michigan"
S_MINNESOTA = "Minnesota"
S_MISSISSIPPI = "Mississippi"
S_MISSOURI = "Missouri"
S_MONTANA = "Montana"
S_NEBRASKA = "Nebraska"
S_NEBRASKA1 = "Nebraska First Congressional District"
S_NEBRASKA2 = "Nebraska Second Congressional District"
S_NEBRASKA3 = "Nebraska Third Congressional District"
S_NEVADA = "Nevada"
S_NEW_HAMPSHIRE = "New Hampshire"
S_NEW_JERSEY = "New Jersey"
S_NEW_MEXICO = "New Mexico"
S_NEW_YORK = "New York"
S_NORTH_CAROLINA = "North Carolina"
S_NORTH_DAKOTA = "North Dakota"
S_NORTHERN_MARIANA_ISLANDS = "Northern Mariana Islands"
S_OHIO = "Ohio"
S_OKLAHOMA = "Oklahoma"
S_OREGON = "Oregon"
S_PENNSYLVANIA = "Pennsylvania"
S_PUERTO_RICO = "Puerto Rico"
S_RHODE_ISLAND = "Rhode Island"
S_SOUTH_CAROLINA = "South Carolina"
S_SOUTH_DAKOTA = "South Dakota"
S_TENNESSEE = "Tennessee"
S_TEXAS = "Texas"
S_US_VIRGIN_ISLANDS = "US Virgin Islands"
S_UTAH = "Utah"
S_VERMONT = "Vermont"
S_VIRGINIA = "Virginia"
S_WASHINGTON = "Washington"
S_WEST_VIRGINIA = "West Virginia"
S_WISCONSIN = "Wisconsin"
S_WYOMING = "Wyoming"
S_USA = "USA"

# R_ represents a region of the US.
R_NORTH = "North"
R_WEST = "West"
R_MIDWEST = "Midwest"
R_SOUTH = "South"
R_PACIFIC = "Pacific"
R_WORLD = "World"

# T_ represents a type of territory.
T_STATE = "State"
T_TERRITORY = "Territory"
T_DC = "District of Columbia"
T_DISTRICT = "District"
T_ORG = "Organisation"

# Q_ represents a type of question asked in a poll.
Q_PRIMARY = "Primary"